export interface DetectedPattern {
  type: 'sequence' | 'repeat' | 'keyboard-walk' | 'date' | 'common';
  match: string;
  start: number;
}

const SEQUENCES: string[] = [
  'abcdefghijklmnopqrstuvwxyz',
  'qwertyuiop',
  'asdfghjkl',
  'zxcvbnm',
  '0123456789',
];

const COMMON: ReadonlySet<string> = new Set<string>([
  'password',
  'passw0rd',
  'p@ssw0rd',
  'qwerty',
  'qwerty123',
  'letmein',
  'welcome',
  'admin',
  'admin123',
  'administrator',
  'root',
  'toor',
  'iloveyou',
  'monkey',
  'dragon',
  'sunshine',
  'princess',
  'football',
  'baseball',
  'basketball',
  'superman',
  'batman',
  'starwars',
  'pokemon',
  'master',
  'shadow',
  'hello',
  'world',
  'dog',
  'cat',
  'fish',
  'bird',
  'horse',
  'cow',
  'pig',
  'rex',
  'max',
  'buddy',
  'luna',
  'rocky',
  'duke',
  'bear',
  'tiger',
  'lion',
  'wolf',
  'fox',
  'pet',
  'puppy',
  'kitty',
  'animal',
  'paws',
  'spot',
  'rover',
  'fido',
  'fluffy',
  'whiskers',
  'mittens',
  'socks',
  'ginger',
  'coco',
  'lucky',
  'shadow',
  'oreo',
  'simba',
  'nala',
  'milo',
  'oscar',
  'bella',
  'loki',
  'oliver',
  'tucker',
  'bailey',
  'dexter',
  'murphy',
  'sadie',
  'maggie',
  'chloe',
  'daisy',
  'lily',
  'zoe',
  'sophie',
  'luna',
  'ruby',
  'stella',
  'rosie',
  'piper',
  'name',
  'named',
  'nameis',
  'called',
  'calls',
  'nick',
  'nickname',
  'birthday',
  'wedding',
  'anniversary',
  'foo',
  'bar',
  'baz',
  'test',
  'test123',
  'changeme',
  'default',
  'guest',
  'hello123',
  'welcome1',
  '123abc',
  'abcdef',
  'asdfgh',
  'asdf1234',
  'azerty',
  'zaq12wsx',
  'trustno1',
  'michael',
  'jennifer',
  'jessica',
  'ashley',
  'amanda',
  'brandon',
  'nicole',
  'daniel',
  'hello1',
  'freedom',
  'money',
  'love',
  'you',
  'iloveu',
  'thankyou',
  'fuck',
  'fuckyou',
  'shit',
  'bitch',
  'asshole',
  'bastard',
  'damn',
  'bloody',
  'crap',
  'dick',
  'pussy',
  'tits',
  'boob',
  'asshole',
  'stupid',
  'dumb',
  'idiot',
  'moron',
  'retard',
  'gay',
  'queer',
  'fag',
  'nigga',
  'nigger',
  'ass',
  'damnit',
  'wtf',
  'omg',
  'lol',
  'lmao',
  'rofl',
  'afaik',
  'imo',
  'tbh',
  'fyi',
  'brb',
  'ttyl',
  'smh',
  'idk',
  'idc',
  'ty',
  'jk',
  'bet',
  'sus',
  'slay',
  'queen',
  'king',
  'princess',
  'prince',
  'lord',
  'kingboss',
  'gaming',
  'gamer',
  'play',
  'playboy',
  'player',
  'winner',
  'boss',
  'bossman',
  'bossman1',
  'hack',
  'hacker',
  'h4ck3r',
  'crypto',
  'bitcoin',
  'eth',
  'ethereum',
  'trading',
  'trader',
  'forex',
  'money',
  'cash',
  'dollars',
  'dollar',
  'euro',
  'pound',
  'euro123',
  'money123',
  'cash123',
  'bank',
  'banking',
  'bank123',
  'paypal',
  'visa',
  'mastercard',
  'secure',
  'security',
  'secret',
  'private',
  'public',
  'admin',
  'admin1',
  'admin12',
  'admin123',
  'test',
  'test1',
  'test12',
  'test123',
  'demo',
  'sample',
  'example',
  'temp',
  'tmp',
  'temp123',
  'hello',
  'world',
  'helloworld',
  'foobar',
  'foobaz',
  'fooboo',
  'foofoo',
  'barbar',
  'bazzbaz',
  'qux',
  'quux',
  'alpha',
  'beta',
  'gamma',
  'delta',
  'epsilon',
  'zeta',
  'eta',
  'theta',
  'iota',
  'kappa',
  'lambda',
  'mu',
  'nu',
  'xi',
  'omicron',
  'pi',
  'rho',
  'sigma',
  'tau',
  'upsilon',
  'phi',
  'chi',
  'psi',
  'omega',
  'winter',
  'spring',
  'summer',
  'autumn',
  'fall',
  'january',
  'february',
  'march',
  'april',
  'may',
  'june',
  'july',
  'august',
  'september',
  'october',
  'november',
  'december',
  'monday',
  'tuesday',
  'wednesday',
  'thursday',
  'friday',
  'saturday',
  'sunday',
  'weekend',
  'weekday',
  'morning',
  'afternoon',
  'evening',
  'night',
  'midnight',
  'noon',
  'today',
  'tomorrow',
  'yesterday',
  'tonight',
  'forever',
  'always',
  'never',
  'sometimes',
  'maybe',
  'perhaps',
  'really',
  'truly',
  'actually',
  'basically',
  'literally',
  'seriously',
  'honestly',
  'apparently',
  'obviously',
  'clearly',
  'simply',
  'easily',
  'quickly',
  'slowly',
  'suddenly',
  'eventually',
  'finally',
  'already',
  'yet',
  'still',
  'also',
  'just',
  'only',
  'even',
  'still',
  'again',
  'once',
  'more',
  'most',
  'much',
  'many',
  'some',
  'any',
  'few',
  'all',
  'both',
  'each',
  'every',
  'other',
  'another',
  'such',
  'same',
  'different',
  'new',
  'old',
  'good',
  'bad',
  'great',
  'big',
  'small',
  'long',
  'short',
  'high',
  'low',
  'right',
  'wrong',
  'true',
  'false',
  'yes',
  'no',
  'maybe',
  'okay',
  'fine',
  'sure',
  'cool',
  'awesome',
  'nice',
  'lovely',
  'perfect',
  'fantastic',
  'amazing',
  'wonderful',
  'beautiful',
  'pretty',
  'cute',
  'handsome',
  'smart',
  'clever',
  'funny',
  'silly',
  'weird',
  'strange',
  'odd',
  'normal',
  'usual',
  'common',
  'rare',
  'unique',
  'special',
  'typical',
  'general',
  'basic',
  'simple',
  'complex',
  'easy',
  'hard',
  'difficult',
  'tough',
  'strong',
  'weak',
  'fast',
  'quick',
  'slow',
  'hot',
  'cold',
  'warm',
  'cool',
  'fresh',
  'clean',
  'dirty',
  'wet',
  'dry',
  'soft',
  'hard',
  'rough',
  'smooth',
  'sharp',
  'dull',
  'bright',
  'dark',
  'light',
  'heavy',
  'light',
  'open',
  'close',
  'shut',
  'start',
  'stop',
  'begin',
  'end',
  'finish',
  'continue',
  'keep',
  'hold',
  'let',
  'make',
  'take',
  'give',
  'get',
  'put',
  'set',
  'send',
  'bring',
  'carry',
  'turn',
  'move',
  'show',
  'hide',
  'cover',
  'reach',
  'leave',
  'pass',
  'cross',
  'hold',
  'catch',
  'draw',
  'hang',
  'break',
  'wear',
  'tear',
  'sell',
  'buy',
  'cost',
  'pay',
  'save',
  'spend',
  'waste',
  'earn',
  'win',
  'lose',
  'miss',
  'complete',
  'total',
  'full',
  'empty',
  'half',
  'whole',
  'part',
  'piece',
  'section',
  'corner',
  'edge',
  'side',
  'top',
  'bottom',
  'front',
  'back',
  'left',
  'right',
  'center',
  'middle',
  'inside',
  'outside',
  'forward',
  'backward',
  'up',
  'down',
  'north',
  'south',
  'east',
  'west',
  'near',
  'far',
  'close',
  'high',
  'low',
  'above',
  'below',
  'under',
  'over',
  'across',
  'through',
  'against',
  'between',
  'among',
  'around',
  'behind',
  'beside',
  'beyond',
  'within',
  'without',
  'before',
  'after',
  'during',
  'since',
  'until',
  'while',
  'because',
  'although',
  'though',
  'even',
  'if',
  'when',
  'where',
  'why',
  'how',
  'what',
  'which',
  'who',
  'whom',
  'whose',
  'this',
  'that',
  'these',
  'those',
  'my',
  'your',
  'his',
  'her',
  'its',
  'our',
  'their',
  'myself',
  'yourself',
  'himself',
  'herself',
  'itself',
  'ourselves',
  'themselves',
  'me',
  'him',
  'her',
  'us',
  'them',
  'mine',
  'yours',
  'his',
  'hers',
  'ours',
  'theirs',
  'is',
  'are',
  'was',
  'were',
  'be',
  'been',
  'being',
  'am',
  'have',
  'has',
  'had',
  'having',
  'do',
  'does',
  'did',
  'doing',
  'will',
  'would',
  'should',
  'could',
  'may',
  'might',
  'must',
  'can',
  'shall',
]);

function reversed(s: string): string {
  return s.split('').reverse().join('');
}

export function detectPatterns(s: string): DetectedPattern[] {
  const out: DetectedPattern[] = [];
  if (s.length === 0) return out;
  const lc = s.toLowerCase();
  // Dedup by (type, start, lowercase match). Same word found by both the
  // substring loop and the word-chunk loop (e.g. "password" in "password123")
  // should only be reported once.
  const seen = new Set<string>();
  const add = (p: DetectedPattern): void => {
    const key = `${p.type}|${p.start}|${p.match.toLowerCase()}`;
    if (seen.has(key)) return;
    seen.add(key);
    out.push(p);
  };

  // Common-word match — only consider words 6+ chars. Shorter substrings like
  // "me", "or", "um" match almost every random string and would cause
  // catastrophic false positives (every random 18-char lowercase string
  // contains "me" and "um" by pure chance).
  for (const w of COMMON) {
    if (w.length < 6) continue;
    const idx = lc.indexOf(w);
    if (idx >= 0) add({ type: 'common', match: s.slice(idx, idx + w.length), start: idx });
    const ridx = lc.indexOf(reversed(w));
    if (ridx >= 0 && ridx !== idx) add({ type: 'common', match: s.slice(ridx, ridx + w.length), start: ridx });
  }

  // Word-boundary match — catches camelCase / PascalCase / kebab / snake / dot
  // concatenations like "MyDog", "my-dog", "my_dog", "myDog". Without this,
  // "MyDog'sNameIsRex!2024" reports ~132 effective bits even though every
  // human can see it's four small dictionary words plus a year.
  //
  // We split on non-letter boundaries AND on case transitions (camelCase),
  // then for each chunk of length 3+ that is also in COMMON, we record it.
  for (const w of wordChunks(s)) {
    const lw = w.toLowerCase();
    if (lw.length < 3 || !COMMON.has(lw)) continue;
    const idx = lc.indexOf(lw);
    if (idx >= 0) add({ type: 'common', match: s.slice(idx, idx + lw.length), start: idx });
  }

  for (const seq of SEQUENCES) {
    for (let len = 4; len <= Math.min(seq.length, s.length); len++) {
      for (let i = 0; i + len <= seq.length; i++) {
        const fwd = seq.slice(i, i + len);
        const rev = reversed(fwd);
        const from = lc.indexOf(fwd);
        if (from >= 0) { add({ type: 'sequence', match: s.slice(from, from + len), start: from }); break; }
        const rfrom = lc.indexOf(rev);
        if (rfrom >= 0) { add({ type: 'sequence', match: s.slice(rfrom, rfrom + len), start: rfrom }); break; }
      }
    }
  }

  const reRepeat = /(.)\1{2,}/g;
  let m: RegExpExecArray | null;
  while ((m = reRepeat.exec(s)) !== null) {
    add({ type: 'repeat', match: m[0], start: m.index });
  }

  const reDate = /\d{4,8}/g;
  while ((m = reDate.exec(s)) !== null) {
    add({ type: 'date', match: m[0], start: m.index });
  }

  return out;
}

/** Return candidate word chunks for the secondary dictionary match.
 *  - Splits on non-letter characters (digits, punctuation, separators).
 *  - Also splits on case transitions: "MyDog" -> ["My", "Dog"]. */
function* wordChunks(s: string): Generator<string> {
  const spaced = s.replace(/[^A-Za-z]+/g, ' ');
  const split = spaced.replace(/([a-z])([A-Z])/g, '$1 $2').replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2');
  for (const tok of split.split(/\s+/)) {
    if (tok.length >= 3) yield tok;
  }
}
